sudo: false
language: ruby
cache:
  bundler: true
  directories:
  - $(npm root)
  - ~/bin
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - '2.0'
  - '2.1'
  - '2.2'
  - jruby-19mode
  - ree
script:
  if [ -n "$RUBOCOP" ]; then
    bundle exec rubocop
  ; elif [ -n "$RAILS_VERSION" ]; then
    bundle exec image_optim --info
    && bundle exec rspec spec/image_optim/railtie_spec.rb
  ; else
    bundle exec image_optim --info
    && bundle exec rspec
  ; fi
before_install:
  if [ -z "$RUBOCOP" ]; then
    command -v svgo || npm install svgo
    ;
    command -v pngout || (
      mkdir -p ~/bin
      && curl -L "http://static.jonof.id.au/dl/kenutils/pngout-20130221-linux.tar.gz" | tar -xz -C ~/bin --strip-components 2 --wildcards '*/x86_64/pngout'
    )
  ; fi
matrix:
  fast_finish: true
  include:
    - env: RAILS_VERSION='~> 3.2'
      rvm: default
    - env: RAILS_VERSION='~> 4.0.0'
      rvm: default
    - env: RAILS_VERSION='~> 4.1.0'
      rvm: default
    - env: RAILS_VERSION='~> 4.2.0'
      rvm: default
    - env: RUBOCOP=true
      rvm: default
  allow_failures:
    - rvm: jruby-19mode
addons:
  code_climate:
    repo_token:
      secure: FDikT3JnOJHOAFSaKwVPB1VOphU0sSzAnzQ+YjSt9XFE+9uFQHth/j4rFoVoqALhCj+47trv6spwkbcSjGCVzm+87OI80GkLCCzNjDOz2W4sP9JWItVgS1VoWW+ioPxpLgpguTb3wutwKOUMEAf+40EX657ZiHumM7nNHrF+RCU=
